In [1]:
import numpy as np
x=np.arange(10).reshape(5,2)
y=range(5)

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test=train_test_split(x,y)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

model.predict([[13,14]])

array([6.5])

In [2]:
print("Input" , x)

Input [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
import pickle

with open('LRmodel.pkl','wb') as f:
    pickle.dump(model,f)

In [4]:
with open('LRmodel.pkl','rb') as f:
    saved_model=pickle.load(f)

In [5]:
saved_model

LinearRegression()

In [6]:
saved_model.predict([[100,101]])

array([50.])

Joblib is used when there is more numerical data

In [7]:
import joblib

In [8]:
f1='LR_model.sav'

In [9]:
joblib.dump(model,f1)

['LR_model.sav']

In [10]:
joblib_model=joblib.load(f1)

In [11]:
joblib_model.predict([[10,11]])

array([5.])

In [ ]:
from flask import Flask, jsonify, request
import pickle

app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World"

@app.route('/input/<int:x1>/<int:x2>/')
def check(x1, x2):
    print(x1, "", x2)
    fp = open('LRmodel.pkl', "rb")
    saved_model = pickle.load(fp)

    # Predict the Output Y where input is X1 & X2
    predictedY = saved_model.predict([[x1, x2]])

    print("Output is ", predictedY)
    return "Y: " + str(predictedY[0])

app.run(host='0.0.0.0' , port=106)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on all addresses.
 * Running on http://192.168.170.118:106/ (Press CTRL+C to quit)
192.168.170.118 - - [01/May/2024 13:18:49] "GET / HTTP/1.1" 200 -


10  11


192.168.170.118 - - [01/May/2024 13:19:11] "GET /input/10/11/ HTTP/1.1" 200 -


Output is  [5.]


In [ ]:
http://192.168.178.118:106/input/10/11/