In [ ]:
Name : Mahek Shah , ID : 22000248 , Batch A

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.randn(1)

array([-0.94124434])

In [10]:
np.random.randn(25)

array([-9.12471752e-01, -1.69371369e+00, -7.16301146e-01,  1.56669944e+00,
        2.98096666e-01, -2.50370209e-01,  8.44785492e-01,  1.99728614e-01,
        8.64213694e-01, -3.37202235e-02, -1.09072571e+00, -5.82273211e-02,
        9.38092512e-02, -1.43091879e-04,  7.22327752e-01,  4.01194276e-01,
       -7.22241731e-01,  5.83136887e-01, -1.37013121e+00,  1.74586181e+00,
        1.10189125e+00, -9.90065791e-01, -1.41713283e-01,  6.52537560e-01,
       -5.35715330e-03])

In [11]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [16]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[3:4,4:]

array([[20]])

In [17]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[4]

array([21, 22, 23, 24, 25])

In [19]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
sum(a)

array([55, 60, 65, 70, 75])

In [21]:
a.sum()

325

In [3]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a.var()

52.0

In [4]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a.min()

1

In [5]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a.max()

25

In [22]:
a.std()

7.211102550927978

In [23]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

In [24]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [25]:
d=np.arange(13)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
m=np.arange(6).reshape(2,3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
n=np.arange(1,13).reshape(3,2,2)
n

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [28]:
c=np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [29]:
c.dtype

dtype('int32')

In [35]:
c.shape

(2, 2)

In [36]:
c.ndim

2

In [31]:
m.shape

(2, 3)

In [37]:
m.ndim

2

In [32]:
n.shape

(3, 2, 2)

In [38]:
n.ndim

3

In [33]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [42]:
maths_marks=np.random.randint(1,100,20)
maths_marks

array([58, 76, 87, 23, 30, 80, 85, 11, 53, 88, 47, 54, 78,  2, 66, 84, 89,
       92, 99, 41])

In [43]:
np.sort(maths_marks)

array([ 2, 11, 23, 30, 41, 47, 53, 54, 58, 66, 76, 78, 80, 84, 85, 87, 88,
       89, 92, 99])

In [48]:
asc=2, 11, 23, 30, 41, 47, 53, 54, 58, 66, 76, 78, 80, 84, 85, 87, 88, 89, 92, 99
np.flip(asc)

array([99, 92, 89, 88, 87, 85, 84, 80, 78, 76, 66, 58, 54, 53, 47, 41, 30,
       23, 11,  2])

In [49]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.eye(5,5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [52]:
np.eye(5,5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [53]:
np.eye(5,5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [55]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
np.split?

In [62]:
x=np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [69]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
np.split(v,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [71]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [72]:
np.random.uniform?


In [81]:
s=np.random.uniform(0,9,10)
s

array([7.85335694, 7.81298579, 0.21198744, 4.56791383, 5.4786444 ,
       8.14430257, 4.53558145, 1.57204379, 2.71385697, 1.42437241])

In [82]:
np.ceil(s)

array([8., 8., 1., 5., 6., 9., 5., 2., 3., 2.])

In [83]:
np.floor(s)

array([7., 7., 0., 4., 5., 8., 4., 1., 2., 1.])

In [85]:
np.round(s,decimals=2)

array([7.85, 7.81, 0.21, 4.57, 5.48, 8.14, 4.54, 1.57, 2.71, 1.42])

In [90]:
h=np.arange(0,25).reshape(5,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
h.min(axis=0)

array([0, 1, 2, 3, 4])

In [96]:
h.max(axis=0)

array([20, 21, 22, 23, 24])

In [97]:
h.var(axis=0)

array([50., 50., 50., 50., 50.])

In [98]:
h.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [106]:
mv=np.arange(100,151)
mv

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [107]:
np.flip(mv)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [102]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
dh=np.array([1,2,3,4,5])
dh

array([1, 2, 3, 4, 5])

In [116]:
hd=(1,0,2,0,0,4,0,8)
hd

(1, 0, 2, 0, 0, 4, 0, 8)

In [117]:
np.nonzero(hd)

(array([0, 2, 5, 7], dtype=int64),)

In [134]:
z=np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [135]:
z[1:9,1:9]=0

In [136]:
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
import numpy as np
r=np.zeros((5,5),dtype=int)
r[::2,::2]=1
r[1::2,1::2]=1
r

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [6]:
import numpy as np

def create_matrix_with_border_nan(rows, cols):
    matrix = np.full((rows, cols), np.nan)  # Create a matrix filled with NaN
    matrix[1:-1, 1:-1] = 0  # Fill inner values with 0
    return matrix

# Example usage:
rows = 5
cols = 4
result_matrix = create_matrix_with_border_nan(rows, cols)
print(result_matrix)


[[nan nan nan nan]
 [nan  0.  0. nan]
 [nan  0.  0. nan]
 [nan  0.  0. nan]
 [nan nan nan nan]]


In [7]:
# Original sorted array
original_array = [1, 2, 3, 4, 5]

# Deep copy of the sorted array using slicing
copied_array = original_array[:]

# Print the copied array
print("Copied array:", copied_array)

Copied array: [1, 2, 3, 4, 5]
